/**
 * Applies the schema and loads the database.
 *
 * Reference data (settlements, road distances) comes from the files built by
 * fetch-settlements.mjs and build-distance-matrix.mjs. Demand is generated by
 * lib/seed.ts from the region's own structure.
 *
 * Run against the local PGlite database:   npm run db:seed
 * Run against Neon:                        DATABASE_URL=postgres://… npm run db:seed
 */

import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { getDb } from "../lib/db.ts";
import { DEFAULT_SEED_CONFIG, generateSeed } from "../lib/seed.ts";
import type { Settlement } from "../lib/types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

interface MatrixPair {
  from: string;
  to: string;
  km: number;
  minutes: number;
  source: "osrm" | "estimated";
}

/**
 * Postgres has a hard cap on bind parameters per statement, so rows go in
 * batches rather than one enormous insert.
 */
async function insertBatched(
  table: string,
  columns: string[],
  rows: unknown[][],
  batchSize = 200,
): Promise<void> {
  const db = getDb();
  for (let start = 0; start < rows.length; start += batchSize) {
    const batch = rows.slice(start, start + batchSize);
    const values: unknown[] = [];
    const tuples = batch.map((row) => {
      const placeholders = row.map((value) => {
        values.push(value);
        return `$${values.length}`;
      });
      return `(${placeholders.join(", ")})`;
    });
    await db.query(
      `INSERT INTO ${table} (${columns.join(", ")}) VALUES ${tuples.join(", ")}`,
      values,
    );
  }
}

async function main() {
  const db = getDb();
  console.log(`Seeding via ${db.backend}…`);

  const settlementsFile = JSON.parse(
    await readFile(join(ROOT, "data", "settlements.json"), "utf8"),
  ) as { settlements: Settlement[] };
  const matrixFile = JSON.parse(
    await readFile(join(ROOT, "data", "distance-matrix.json"), "utf8"),
  ) as { pairs: MatrixPair[]; detour_factor: number };

  const settlements = settlementsFile.settlements;
  const known = new Set(settlements.map((s) => s.id));

  console.log("  applying schema");
  await db.exec(await readFile(join(ROOT, "db", "schema.sql"), "utf8"));

  console.log(`  settlements: ${settlements.length}`);
  await insertBatched(
    "settlements",
    ["id", "osm_id", "name_kz", "name_ru", "place", "population", "lat", "lon"],
    settlements.map((s) => [s.id, s.osm_id ?? null, s.name_kz, s.name_ru, s.place, s.population, s.lat, s.lon]),
  );

  // Stored in both directions so the app can look a pair up without normalising
  // the argument order at every call site.
  const distanceRows: unknown[][] = [];
  for (const pair of matrixFile.pairs) {
    if (!known.has(pair.from) || !known.has(pair.to)) continue;
    distanceRows.push([pair.from, pair.to, pair.km, pair.minutes, pair.source]);
    distanceRows.push([pair.to, pair.from, pair.km, pair.minutes, pair.source]);
  }
  console.log(`  distances: ${distanceRows.length} directed rows`);
  await insertBatched("distances", ["from_id", "to_id", "km", "minutes", "source"], distanceRows);

  const { carriers, vehicles, orders } = generateSeed(settlements, {
    ...DEFAULT_SEED_CONFIG,
    now: new Date("2026-08-19T06:00:00Z"),
  });

  console.log(`  carriers: ${carriers.length}, vehicles: ${vehicles.length}, orders: ${orders.length}`);
  await insertBatched(
    "carriers",
    ["id", "name", "phone", "base_id"],
    carriers.map((c) => [c.id, c.name, c.phone, c.base_id]),
  );
  await insertBatched(
    "vehicles",
    ["id", "carrier_id", "plate", "kind", "capacity_kg", "fuel_per_100km", "at_id"],
    vehicles.map((v) => [v.id, v.carrier_id, v.plate, v.kind, v.capacity_kg, v.fuel_per_100km, v.at_id]),
  );
  await insertBatched(
    "orders",
    [
      "id", "shipper_name", "origin_id", "destination_id", "cargo", "weight_kg",
      "needs_cooling", "ready_at", "deadline_at", "status", "raw_text", "parsed_by",
    ],
    orders.map((o) => [
      o.id, o.shipper_name, o.origin_id, o.destination_id, o.cargo, o.weight_kg,
      o.needs_cooling, o.ready_at, o.deadline_at, o.status, o.raw_text ?? null, o.parsed_by ?? "seed",
    ]),
  );

  const [counts] = await db.query<{ settlements: string; distances: string; orders: string; vehicles: string }>(
    `SELECT
       (SELECT count(*) FROM settlements) AS settlements,
       (SELECT count(*) FROM distances)   AS distances,
       (SELECT count(*) FROM orders)      AS orders,
       (SELECT count(*) FROM vehicles)    AS vehicles`,
  );

  console.log("\nSeeded:", counts);

  const weights = await db.query<{ bucket: string; n: string }>(
    `SELECT CASE
              WHEN weight_kg < 1000 THEN 'мелкие (<1 т)'
              WHEN weight_kg < 3000 THEN 'средние (1–3 т)'
              ELSE 'крупные (>3 т)'
            END AS bucket, count(*) AS n
     FROM orders GROUP BY 1 ORDER BY 2 DESC`,
  );
  console.log("\nЗаявки по весу:");
  for (const row of weights) console.log(`  ${row.bucket.padEnd(18)} ${row.n}`);

  const directions = await db.query<{ direction: string; n: string }>(
    `SELECT o.place || ' → ' || d.place AS direction, count(*) AS n
     FROM orders
     JOIN settlements o ON o.id = orders.origin_id
     JOIN settlements d ON d.id = orders.destination_id
     GROUP BY 1 ORDER BY 2 DESC`,
  );
  console.log("\nНаправления:");
  for (const row of directions) console.log(`  ${row.direction.padEnd(20)} ${row.n}`);
}

main().catch((err) => {
  console.error("\nSEED FAILED:", err);
  process.exit(1);
});
